[build]
target-dir = ".cache/cargo-build"

[env]
RUST_BACKTRACE = "1"

[profile.dev]
split-debuginfo = "unpacked"
opt-level = 1

[profile.profile]
inherits = "release"
debuginfo = true

[profile.product]
inherits = "release"
lto = "thin"
codegen-units = 1

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=/usr/bin/mold"]

# Ref: https://docs.shipyard.rs/configuration/git-fetch-with-cli.html
[net]
git-fetch-with-cli = true

[source]
crates-io = { replace-with = "rsproxy-sparse" }
rsproxy-sparse = { registry = "sparse+https://rsproxy.cn/index/" }

# Ref: https://github.com/nabijaczleweli/cargo-update#source-replacement-vs-custom-registries
[registries]
rsproxy-sparse = { index = "sparse+https://rsproxy.cn/index/" }
