[build]
target-dir = ".cache/cargo-build"

[env]
RUST_BACKTRACE = "1"

[profile.dev]
split-debuginfo = "unpacked"

[profile.bench]
debug = true
split-debuginfo = "unpacked"

[profile.product]
inherits = "release"
strip = true
lto = "thin"
codegen-units = 1
# panic = "abort"

# Ref: https://docs.shipyard.rs/configuration/git-fetch-with-cli.html
[net]
git-fetch-with-cli = true

[source]
crates-io.replace-with = "ustc"
ustc.registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

# Ref: https://github.com/nabijaczleweli/cargo-update#source-replacement-vs-custom-registries
[registries]
ustc.index = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"
