[build]
target-dir = ".cargo/target"

[cargo-new]
name = "QuarticCat"
email = "<QuarticCat@protonmail.com>"

[profile.dev]
split-debuginfo = "unpacked"
# opt-level = 1
# package."*".opt-level = 3    # override dependencies
# build-override.opt-level = 3 # override build scripts and proc-macros

# Applied through `cargo build --profile release-debug`
[profile.release-debug]
inherits = "release"
debuginfo = true

# Applied through `cargo build --profile release-product`
[profile.release-product]
inherits = "release"
lto = "thin"
strip = true

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]
# TODO: shared generics

[http]
proxy = "socks5://127.0.0.1:1089"

[source]
# crates-io = { replace-with = "tuna" }
tuna = { registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git" }
ustc = { registry = "git://mirrors.ustc.edu.cn/crates.io-index" }
sjtu = { registry = "https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index" }
rustcc = { registry = "git://crates.rustcc.cn/crates.io-index" }

# Required by cargo-update
# Ref: https://github.com/nabijaczleweli/cargo-update#source-replacement-vs-custom-registries
[registries]
tuna = { index = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git" }
ustc = { index = "git://mirrors.ustc.edu.cn/crates.io-index" }
sjtu = { index = "https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index" }
rustcc = { index = "git://crates.rustcc.cn/crates.io-index" }
