# Based on clangd-14

CompileFlags:
  Compiler: clang++
  Add: [-std=c++20, -Wall, -Wextra, -march=native]

Diagnostics:
  ClangTidy:
    Add: [bugprone-*, performance-*] # TODO: add more

Hover:
  ShowAKA: Yes
