# Based on clangd-14

CompileFlags:
  Compiler: clang++
  Add: [-Wall, -Wextra, -march=native, -std=c++20]

Diagnostics:
  ClangTidy:
    Add: [bugprone-*, performance-*] # TODO: add more

Hover:
  ShowAKA: Yes
